experiments:
  t2plinker:
    - t2plinker
  tctracer-2020:
    - tctracer-2020
  tctracer-2022:
    - tctracer-2022
  testlinker:
    - testlinker

groups:
  tctracer-plus:
    - tctracer-2020
    - tctracer-2022
  testlinker-plus:
    - tctracer-2020
    - tctracer-2022
    - testlinker
  t2plinker-plus:
    - tctracer-2020
    - tctracer-2022
    - testlinker
    - t2plinker
